model:
  class_path: default.FeatureExtractor.FeatureExtractor
  init_args:
    model_name_or_path: null
    dropout_prob: 0.1
    lr: 2e-5
    weight_decay: 0.01
    scheduler_type: linear
    warmup_steps: 0.1
    freeze: True
