model:
  class_path: K_1_way.K_1_way.K_1_way
  init_args:
    model_name_or_path: null
    dropout_prob: 0.1
    lr: 2e-5
    weight_decay: 0.0
    scheduler_type: linear
    warmup_steps: 0.1
    freeze: false
    