model:
  class_path: ours_sr.ours_sr_local.OurSRLocal
  init_args:
    model_name_or_path: null
    lr: 2.0e-5 #1.0e-03 
    weight_decay: 0.01
    scheduler_type: linear 
    # warmup_steps: 0
    warmup_rate: 0.1
    freeze: false
    l: 0.3
